# Generated by Django 2.2.1 on 2020-04-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoroApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDefu', models.CharField(max_length=100)),
                ('birth', models.DateField()),
                ('defunct', models.DateField()),
                ('description', models.CharField(max_length=300)),
                ('public', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('dniAlta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('dniAlta', models.CharField(max_length=100)),
                ('nombreDefu', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUser', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
            ],
        ),
    ]
